app/routes.php
<?php

Route::resource('admin/sections', 'AdminSectionsController');

Route::get('/', function()
{
    return View::make('hello');
});

app/filters.php
<?php

/*
|--------------------------------------------------------------------------
| Application & Route Filters
|--------------------------------------------------------------------------
|
| Below you will find the "before" and "after" events for the application
| which may be used to do any work before or after a request into your
| application. Here you may also register your custom route filters.
|
*/

App::before(function($request)
{
	//
});


App::after(function($request, $response)
{
	//
});

/*
|--------------------------------------------------------------------------
| Authentication Filters
|--------------------------------------------------------------------------
|
| The following filters are used to verify that the user of the current
| session is logged into this application. The "basic" filter easily
| integrates HTTP Basic authentication for quick, simple checking.
|
*/

Route::filter('auth', function()
{
	if (Auth::guest())
	{
		if (Request::ajax())
		{
			return Response::make('Unauthorized', 401);
		}
		else
		{
			return Redirect::guest('login');
		}
	}
});


Route::filter('auth.basic', function()
{
	return Auth::basic();
});

/*
|--------------------------------------------------------------------------
| Guest Filter
|--------------------------------------------------------------------------
|
| The "guest" filter is the counterpart of the authentication filters as
| it simply checks that the current user is not logged in. A redirect
| response will be issued if they are, which you may freely change.
|
*/

Route::filter('guest', function()
{
	if (Auth::check()) return Redirect::to('/');
});

/*
|--------------------------------------------------------------------------
| CSRF Protection Filter
|--------------------------------------------------------------------------
|
| The CSRF filter is responsible for protecting your application against
| cross-site request forgery attacks. If this special token in a user
| session does not match the one given in this request, we'll bail.
|
*/

Route::filter('csrf', function()
{
	if (Session::token() != Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

app/controllers/AdminSectionsController.php
<?php

use Cms\Section\SectionRepoInterface;

class AdminSectionsController extends \BaseController {

    protected $rules = array(
        'name'     => 'required',
        'slug_url' => 'required',
        'type'     => 'required|in:page,blog',
        'menu'     => 'in:1,0',
        'published' => 'in:1,0',
        'menu_order' => 'integer'
    );

    protected $sectionRepo;

    public function __construct(SectionRepoInterface $sectionRepo)
    {
        $this->sectionRepo = $sectionRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $sections = $this->sectionRepo->search(Input::all(), \Cms\Base\BaseRepo::PAGINATE);

        return View::make('admin/sections/list', compact('sections'));
    }

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        return View::make('admin/sections/create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
        $data = Input::all();

        $validator = Validator::make($data, $this->rules);

        if ($validator->passes())
        {
            $section = $this->sectionRepo->create($data);
            return Redirect::to('admin/sections/'. $section->id);
        }
        else
        {
            return Redirect::back()->withInput()->withErrors($validator->messages());
        }

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        $section = $this->sectionRepo->findOrFail($id);
        return View::make('admin/sections/show')->with('section', $section);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $section = $this->sectionRepo->findOrFail($id);
        return View::make('admin/sections/edit')->with('section', $section);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
        $section = $this->sectionRepo->findOrFail($id);

        $data = Input::all();

        $validator = Validator::make($data, $this->rules);

        if ($validator->passes())
        {
            $section = $this->sectionRepo->update($section, $data);
            return Redirect::route('admin.sections.show', $section->id);
        }
        else
        {
            return Redirect::back()->withInput()->withErrors($validator->messages());
        }
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
        $this->sectionRepo->delete($id);
        return Redirect::route('admin.sections.index');
	}


}

app/controllers/BaseController.php
<?php

class BaseController extends Controller {

	/**
	 * Setup the layout used by the controller.
	 *
	 * @return void
	 */
	protected function setupLayout()
	{
		if ( ! is_null($this->layout))
		{
			$this->layout = View::make($this->layout);
		}
	}

}

app/controllers/HomeController.php
<?php

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/

	public function showWelcome()
	{
		return View::make('hello');
	}

}

app/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@yield('title', 'Admin CMS')</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    {{ HTML::style('assets/css/admin.css') }}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">#ProgramemosUnCMS en duilio.me</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      @yield('content')

    </div><!-- /.container -->

    <div class="container">
        <hr/>
        <p>Programando un CMS con Laravel en duilio.me</p>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/admin/news/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

    {{ Form::open(['route' => 'admin.news.store', 'method' => 'POST']) }}

        <button type="submit">Enviar Formulario</button>

    {{ Form::close() }}
</body>
</html>

app/views/admin/news/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

    <h1>Editando noticia {{ $id }}</h1>

    {{ Form::open(['route' => ['admin.news.destroy', $id], 'method' => 'DELETE']) }}

        <button type="submit">Actualizar noticia</button>

    {{ Form::close() }}
</body>
</html>

app/views/admin/sections/create.blade.php
@extends('admin/layout')

@section('title')
    New section
@stop

@section('content')

<h1>New section</h1>

{{ Form::open(['url' => 'admin/sections', 'method' => 'POST']) }}

    @include ('admin/sections/partials/fields')

    <p>
        {{ Form::submit('Create section') }}
    </p>

{{ Form::close() }}

@stop

app/views/admin/sections/edit.blade.php
@extends('admin/layout')

@section('title')
    Edit section "{{ $section->name }}"
@stop

@section('content')

<h1>Edit section "{{ $section->name }}"</h1>

{{ Form::model($section, ['route' => ['admin.sections.update', $section->id], 'method' => 'PUT']) }}

    @include ('admin/sections/partials/fields')

    <p>
        {{ Form::submit('Update section') }}
    </p>

{{ Form::close() }}

@stop

app/views/admin/sections/list.blade.php
@extends('admin/layout')

@section('content')

<h1>Sections</h1>

<p>
    <a href="{{ url('admin/sections/create') }}">
        Add a new section
    </a>
</p>

@include('admin/sections/partials/filters')

@if($sections->getTotal())

    <p>
    There are {{ $sections->getTotal() }} sections, showing page {{ $sections->getCurrentPage() }} of {{ $sections->getLastPage() }}
    </p>

    @include('admin/sections/partials/table')

    {{ $sections->links() }}

@else

    <h4>
    There are no sections, please create the first one
    </h4>

@endif

@stop

app/views/admin/sections/partials/fields.blade.php
    <p>
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name') }}
        {{ $errors->first('name', '<p class="error">:message</p>') }}
    </p>

    <p>
        {{ Form::label('slug_url', 'Slug URL') }}
        {{ Form::text('slug_url') }}
        {{ $errors->first('slug_url', '<p class="error">:message</p>') }}
    </p>

    <p>
        {{ Form::label('type', 'Type') }}
        {{ Form::select('type', ['' => 'Select', 'page' => 'Page', 'blog' => 'Blog']) }}
        {{ $errors->first('type', '<p class="error">:message</p>') }}
    </p>

    <p>
        <label>
            {{ Form::radio('menu', 1) }}
            Show in menu
        </label>
        <label>
            {{ Form::radio('menu', 0) }}
            Don't show in menu
        </label>
        {{ $errors->first('menu', '<p class="error">:message</p>') }}
    </p>

    <p>
        {{ Form::label('menu_order', 'Menu Order') }}
        {{ Form::text('menu_order') }}
        {{ $errors->first('menu_order', '<p class="error">:message</p>') }}
    </p>

    <p>
        <label>
            {{ Form::radio('published', 1) }}
            Published
        </label>
        <label>
            {{ Form::radio('published', 0) }}
            Draft
        </label>
        {{ $errors->first('published', '<p class="error">:message</p>') }}
    </p>

app/views/admin/sections/partials/filters.blade.php
{{ Form::model(Input::all(), ['route' => 'admin.sections.index', 'method' => 'GET']) }}

    {{ Form::text('search') }}
    {{ Form::select('published', ['' => 'Select status', '0' => 'Draft', '1' => 'Published']) }}
    {{ Form::select('menu', ['' => 'Menu status', '0' => 'Not in menu', '1' => 'Show in menu']) }}
    {{ Form::button('Filter sections', ['type' => 'submit', 'class' => 'btn btn-primary']) }}

{{ Form::close() }}

app/views/admin/sections/partials/table.blade.php
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Slug URL</th>
            <th>Menu</th>
            <th>Published</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($sections as $section)
        <tr>
            <td class="name">{{ $section->name }}</td>
            <td>{{ $section->slug_url }}</td>
            <td>{{ $section->menu ? 'Show in menu' : "Don't show in menu" }}</td>
            <td>{{ $section->published ? 'Published' : 'Draft' }}</td>
            <td>
                <a href="{{ route('admin.sections.show', $section->id) }}">Show</a>
                <a href="{{ route('admin.sections.edit', $section->id) }}" class="btn-edit">Edit section</a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

app/views/admin/sections/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

<h1>{{ $section->name }}</h1>

<p>
    <a href="{{ route('admin.sections.edit', $section->id) }}" class="btn-edit">
        Edit section
    </a>
    {{ Form::open(['route' => ['admin.sections.destroy', $section->id], 'method' => 'DELETE']) }}
        {{ Form::button('Delete section', ['type' => 'submit', 'class' => 'btn-del']) }}
    {{ Form::close() }}
</p>

<table>
    <tr>
        <th>Slug URL:</th>
        <td class="slug-url">{{ $section->slug_url }}</td>
        <th>Menu order:</th>
        <td class="menu-order">{{ $section->menu_order }}</td>
    </tr>
    <tr>
        <th>Menu:</th>
        <td class="menu">
            {{ $section->menu ? 'Show in menu' : "Don't show in menu" }}
        </td>
        <th>Status:</th>
        <td class="published">{{ $section->published ? 'Published' : 'Draft' }}</td>
    </tr>
</table>
</body>
</html>